<div id="portfolio" class="container-fluid text-center">
    <div class="col-md-6 text-center slideanim centered">
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/paris.jpg">
                <p><strong>Paris</strong></p>
                <p>Yes, we built Paris</p>
            </div>
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/green-elephant.jpg">
                <p><strong>Inchoo</strong></p>
                <p>Inchoo elephant</p>
            </div>
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/butter.jpeg">
                <p><strong>Butterfly</strong></p>
                <p>nice butterfly</p>
            </div>
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/nice.jpg">
                <p><strong>Nice</strong></p>
                <p>nice picture</p>
            </div>
        </div>
    </div>
</div>

