<div id="portfolio" class="container-fluid text-center">
    <div class="col-md-6 text-center slideanim centered">
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/paris.jpg">
                <p><strong>Paris</strong></p>
                <p>Yes, we built Paris</p>
                <div class="fb-like pull-right"
                     data-href="http://privserver.ddns.net/picturebox/index.php"
                     data-layout="button" data-action="like"
                     data-size="small" data-show-faces="true"
                     data-share="true"></div>
            </div>
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/green-elephant.jpg">
                <p><strong>Inchoo</strong></p>
                <p>Inchoo elephant</p>
                <div class="fb-like pull-right"
                     data-href="http://privserver.ddns.net/picturebox/public/green-elephant.jpg"
                     data-layout="button" data-action="like"
                     data-size="small" data-show-faces="true"
                     data-share="false"></div>
            </div>y
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/butter.jpeg">
                <p><strong>Butterfly</strong></p>
                <p>nice butterfly</p>
                <div class="fb-like pull-right"
                     data-href="http://privserver.ddns.net/picturebox/public/butter.jpeg"
                     data-layout="button" data-action="like"
                     data-size="small" data-show-faces="true"
                     data-share="false"></div>
            </div>
        </div>
        <div class="row">
            <div class="thumbnail">
                <p>Some text</p>
                <img src="<?php echo App::config('url') ?>public/nice.jpg">
                <p><strong>Nice</strong></p>
                <p>nice picture</p>
                <div class="fb-like pull-right"
                     data-href="http://privserver.ddns.net/picturebox/public/nice.jpg"
                     data-layout="button" data-action="like"
                     data-size="small" data-show-faces="true"
                     data-share="false"></div>
            </div>
        </div>
    </div>
    <div id="fb-root"></div>
    <!--<script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/hr_HR/sdk.js#xfbml=1&version=v2.8&appId=997786960353599";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>-->
</div>
