<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Picturebox</title>

    <!-- Required for Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo App::config('url') ?>public/style.css">
</head>
<body>

<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="nav navbar-nav">
                <a href="<?php echo App::config('url') ?>" class="navbar-left"><img class="img2" src="<?php echo App::config('url') ?>public/logo_text_transparent.png"></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <?php if(isset($isLoggedIn) && $isLoggedIn): ?>
                    <li><a href="<?php echo App::config('url') ?>admin/logout">Logout</a></li>
                <?php else: ?>
                    <li><a href="<?php echo App::config('url') ?>admin/index">Login</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>
</header>

    <!-- Main content from view -->
    <main class="container-fluid">
        <?php echo $content ?>
    </main>
<!--
    <footer class="footer">
        <p class="container">&copy; PHP Akademija, 2016</p>
    </footer>
-->
    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>