<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta property="og:url"           content="http://privserver.ddns.net/picturebox/index.php" />
        <meta property="og:type"          content="website" />
        <meta property="og:title"         content="Picturebox" />
        <meta property="og:description"   content="Instagram knockoff" />
        <meta property="og:image"         content="http://privserver.ddns.net/picturebox/public/logo_text_transparent.png" />
        <title>Picturebox</title>

        <!-- Required for Bootstrap -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="<?php echo App::config('url') ?>public/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?php echo App::config('url') ?>public/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo App::config('url') ?>public/style.css">

    </head>
    <body>
        <!--
        <script>
            window.fbAsyncInit = function() {
                FB.init({
                    appId      : '997786960353599',
                    xfbml      : true,
                    version    : 'v2.8'
                });
            };
        
            (function(d, s, id){
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) {return;}
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>-->
        <header>
            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="nav navbar-nav navbar-left">
                        <li></li><a href="<?php echo App::config('url') ?>" class=""><i class="fa fa-instagram fa-3x" aria-hidden="true"></i><img class="img2" src="<?php echo App::config('url') ?>public/logo_text_transparent.png"></a></li>
                    </div>
                    <div class="nav navbar-nav navbar-right">
                        <?php if (isset($isLoggedIn) && $isLoggedIn): ?>
                            <li><a href="<?php echo App::config('url') ?>upload"><i class="fa fa-upload fa-2x" aria-hidden="true"></i></a></li>
                            <li><a href="<?php echo App::config('url') ?>heart"><i class="fa fa-heart fa-2x" aria-hidden="true"></i></a></li>
                            <li><a href="<?php echo App::config('url') ?>index/logout"><i class="fa fa-user-times fa-2x" aria-hidden="true"></i></a></li>
                        <?php else: ?>
                            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal"><i class="fa fa-user fa-2x" aria-hidden="true"></i></button>
                        <?php endif; ?>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main content from view -->
        <main class="container-fluid">
            <?php echo $content ?>
        </main>
        <!--
            <footer class="footer">
                <p class="container">&copy; PHP Akademija, 2016</p>
            </footer>
        -->
        <!-- Bootstrap JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4>Admin login</h4>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="<?php echo App::config('url') ?>index/submit" class="form">
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="password">Lozinka</label>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>

                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Prijava">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </body>
</html>